apiVersion: apps/v1
kind: Deployment
metadata:
  name: shailendra-nagpapp-deployment
  labels:
    app: nagpapp
spec:
  template:
    metadata:
      name: shailendra-nagpapp-pod-m
      labels:
        app: nagpapp
    spec:
      containers:
      - name: shailendra-nagpapp-container-m
        image: shailu0287/app_shailendrasharma:latest
        ports:
          - containerPort: 80
            protocol: TCP
  replicas: 4
  selector:
    matchLabels:
      app: nagpapp
