apiVersion: apps/v1
kind: Deployment
metadata:
  name: shailendra-nagpapp-deployment
  namespace: kubernetes-cluster-shailendrasharma
  labels:
    app: nagpapp
spec:
  template:
    metadata:
      name: shailendra-nagpapp-pod-m
      labels:
        app: nagpapp
    spec:
      containers:
      - name: shailendra-nagpapp-container-m
        image: shailu0287/app_shailendrasharma:40
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom: 
              configMapKeyRef: 
                name: shailendra-configmap
                key: dotNetEnv
              
  replicas: 1
  selector:
    matchLabels:
      app: nagpapp
