apiVersion: v1
kind: Service
metadata:
  name: nagpapp-service
  namespace: kubernetes-cluster-shailendrasharma
  labels: 
    service: nodeport
spec:  
  type: LoadBalancer
  selector:
    app: nagpapp
  ports:
    - port: 80
      targetPort: 80
